project_id = "zbcoocxxxqcvgoefdunq"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-poll-quorum]
    verify_jwt = false
  [functions.close-expired-polls]
    verify_jwt = false
  [functions.create-notification]
    verify_jwt = true
  [functions.delete-user]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
  [functions.register-task-completion]
    verify_jwt = true
  [functions.send-notification-email]
    verify_jwt = true
  [functions.wallet-auth]
    verify_jwt = false
