/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InstallRouteImport } from './routes/install'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BadgesUserIdRouteImport } from './routes/badges/$userId'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as TagsTagIdRouteImport } from './routes/tags/$tagId'
import { Route as ProfileUserIdTypeRouteImport } from './routes/profile/$userId.$type'
import { Route as ShareTypeIdRouteImport } from './routes/share/$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesUserIdRoute = BadgesUserIdRouteImport.update({
  id: '/badges/$userId',
  path: '/badges/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagIdRoute = TagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdTypeRoute = ProfileUserIdTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => ProfileUserIdRoute,
} as any)
const ShareTypeIdRoute = ShareTypeIdRouteImport.update({
  id: '/share/$type/$id',
  path: '/share/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/badges/$userId': typeof BadgesUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRouteWithChildren
  '/profile/edit': typeof ProfileEditRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags/': typeof TagsIndexRoute
  '/profile/$userId/$type': typeof ProfileUserIdTypeRoute
  '/share/$type/$id': typeof ShareTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/badges/$userId': typeof BadgesUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRouteWithChildren
  '/profile/edit': typeof ProfileEditRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags': typeof TagsIndexRoute
  '/profile/$userId/$type': typeof ProfileUserIdTypeRoute
  '/share/$type/$id': typeof ShareTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/badges/$userId': typeof BadgesUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRouteWithChildren
  '/profile/edit': typeof ProfileEditRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags/': typeof TagsIndexRoute
  '/profile/$userId/$type': typeof ProfileUserIdTypeRoute
  '/share/$type/$id': typeof ShareTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/install'
    | '/quiz'
    | '/reset-password'
    | '/search'
    | '/badges/$userId'
    | '/profile/$userId'
    | '/profile/edit'
    | '/tags/$tagId'
    | '/tags/'
    | '/profile/$userId/$type'
    | '/share/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/install'
    | '/quiz'
    | '/reset-password'
    | '/search'
    | '/badges/$userId'
    | '/profile/$userId'
    | '/profile/edit'
    | '/tags/$tagId'
    | '/tags'
    | '/profile/$userId/$type'
    | '/share/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/install'
    | '/quiz'
    | '/reset-password'
    | '/search'
    | '/badges/$userId'
    | '/profile/$userId'
    | '/profile/edit'
    | '/tags/$tagId'
    | '/tags/'
    | '/profile/$userId/$type'
    | '/share/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  InstallRoute: typeof InstallRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  BadgesUserIdRoute: typeof BadgesUserIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRouteWithChildren
  ProfileEditRoute: typeof ProfileEditRoute
  TagsTagIdRoute: typeof TagsTagIdRoute
  TagsIndexRoute: typeof TagsIndexRoute
  ShareTypeIdRoute: typeof ShareTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges/$userId': {
      id: '/badges/$userId'
      path: '/badges/$userId'
      fullPath: '/badges/$userId'
      preLoaderRoute: typeof BadgesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagId': {
      id: '/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId/$type': {
      id: '/profile/$userId/$type'
      path: '/$type'
      fullPath: '/profile/$userId/$type'
      preLoaderRoute: typeof ProfileUserIdTypeRouteImport
      parentRoute: typeof ProfileUserIdRoute
    }
    '/share/$type/$id': {
      id: '/share/$type/$id'
      path: '/share/$type/$id'
      fullPath: '/share/$type/$id'
      preLoaderRoute: typeof ShareTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileUserIdRouteChildren {
  ProfileUserIdTypeRoute: typeof ProfileUserIdTypeRoute
}

const ProfileUserIdRouteChildren: ProfileUserIdRouteChildren = {
  ProfileUserIdTypeRoute: ProfileUserIdTypeRoute,
}

const ProfileUserIdRouteWithChildren = ProfileUserIdRoute._addFileChildren(
  ProfileUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  InstallRoute: InstallRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  BadgesUserIdRoute: BadgesUserIdRoute,
  ProfileUserIdRoute: ProfileUserIdRouteWithChildren,
  ProfileEditRoute: ProfileEditRoute,
  TagsTagIdRoute: TagsTagIdRoute,
  TagsIndexRoute: TagsIndexRoute,
  ShareTypeIdRoute: ShareTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
